### ISSUE TITLE
请问下拉刷新的时候，内容部分都无法响应点击事件？

### ISSUE THREAD

**Issue by kevinlee85** [liaohuqiu/android-Ultra-Pull-To-Refresh#101]
请问，我在进行下拉刷新的时候，内容均无法响应点击事件？
如何设置和解决这个问题？
谢谢

**Comment by YangShaoXiong** [comment]
同问这个问题！！！

**Comment by liaohuqiu** [comment]
I'am already woking on this issue. :)

**Comment by hth** [comment]
This is very important question and I am waiting for a solution. Can you please add a solution at your earliest. Really looking forward to this solution in main release.

**Comment by liaohuqiu** [comment]
fixed in 376addd.

**Comment by liaohuqiu** [comment]
@hth  will be fixed tonight. UTC +8:00.

**Comment by liaohuqiu** [comment]
@hth  `1.0.9.2-SNAPSHOT` has been published, you can check it. If fixed, I will release this version ASAP.

**Comment by liaohuqiu** [comment]
@kevinlee85 @YangShaoXiong  谢谢两位同学，`1.0.9.2-SNAPSHOT` 发布了，看看有没有问题，如果没问题的话，我发布 release 版本。

**Comment by YangShaoXiong** [comment]
@liaohuqiu Thank you.Question already fix.

**Comment by kevinlee85** [comment]
@liaohuqiu Thank you very much. Please release on the main branch, hence i will setup the last maven dependence on my project to replace my local fix.

**Comment by hth** [comment]
@kevinlee85 Thank you. @liaohuqiu I tested and it works. This is just awesome. Please do not forget to add a `test` for this condition. `test` will make sure tomorrow this feature is not lost in future release.

**Comment by liaohuqiu** [comment]
@hth I've add a demo for this case in the sample project, the `WithLongPressFragment`. Do you have any better idea for UI testing?

**Comment by liaohuqiu** [comment]
`1.0.10` has been released.

**Comment by hth** [comment]
@liaohuqiu automation :)

**Comment by liaohuqiu** [comment]
@hth I also like automation :). Do you have any sample project to refer?

**Comment by hth** [comment]
@liaohuqiu I don't have a project handy right now. The moment I have something, I will share with you.

**Comment by liaohuqiu** [comment]
@hth  I'm looking forward that. Thank you in advance.
