### ISSUE TITLE
使用leakcanary检测到内存泄露

### ISSUE THREAD

**Issue by openproject** [liaohuqiu/android-Ultra-Pull-To-Refresh#103]
截图如下：
![Uploading Screenshot_2015-06-06-21-05-51.png…]()

**Comment by openproject** [comment]
![screenshot_2015-06-06-21-05-51](https://cloud.githubusercontent.com/assets/1212758/8024373/87977d16-0d63-11e5-8b7a-5ee2aef372db.png)

**Comment by lichangadd** [comment]
This may help: https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh/issues/88

**Comment by zejiangPG** [comment]
When you want to use refreshComplete(), you need to check this(mPullToRefreshListView.isRefreshing()).
