### ISSUE TITLE
Missed release tag 1.0.10

### ISSUE THREAD

**Issue by hth** [liaohuqiu/android-Ultra-Pull-To-Refresh#107]
Just letting you know site is missing 1.0.10 release details :)

**Comment by liaohuqiu** [comment]
OH, my mistake. Thank you for your reminder.

**Comment by liaohuqiu** [comment]
And it's done now, Thank you. :+1:

**Comment by hth** [comment]
@liaohuqiu You are welcome and Thank you :)
