### ISSUE TITLE
关于刷新完成后自动定位到第一条的问题

### ISSUE THREAD

**Issue by bodao1115** [liaohuqiu/android-Ultra-Pull-To-Refresh#131]
目标效果：实现像微信查看聊天历史那样的效果，即当向上滑动查看以前的聊天历史时，聊天历史加载出来后，不自动定位到最早的那一条聊天历史，而是停留在当前的位置，再由用户自行手动划上去查看新加载出的聊天历史
目前的情况：在加载出聊天历史后，自动定位到了最早的那一条聊天历史。

请问这个该如何调整或者设置呢？

**Comment by dkzwm** [comment]
setSelection(position)

**Comment by bodao1115** [comment]
setSelection(position)已经试过了，但是会发生抖动，即列表自动定位到第一条后，又马上被setSelection盗第position条，效果非常不好

**Comment by bodao1115** [comment]
其实后来自己仔细想了一下，这个控件设计的是下拉“刷新”，并不是下拉”加载更多“，既然是前者那当然是要自动定位到新加载出来内容的第一条了。如果真的是这样，那么我很可能要另辟蹊径了。

**Comment by liaohuqiu** [comment]
刷新完成之后，有一个 UI 回调，在那里面定位到第一条吧，那样会好些。 :)

**Comment by iielse** [comment]
@bodao1115 你可能走到误区里面了，  试图把手机屏幕反过来倒着看。

将下拉加载历史， 理解为 上拉加载历史。

```
layChat.apply {
            layoutManager = LinearLayoutManager(context, LinearLayoutManager.VERTICAL, true)
}
```
这样你可以用 `LoadingViewHolder`这种方法来做。 这个查看历史的功能可能其实并不需要这个 强大的刷新框架
