### ISSUE TITLE
不管我WebView内容上拉滑动到哪里，往下拉总会触发下拉刷新

### ISSUE THREAD

**Issue by aqiansunboy** [liaohuqiu/android-Ultra-Pull-To-Refresh#140]
![image](https://cloud.githubusercontent.com/assets/6840638/9516398/f7ce4360-4cda-11e5-90b0-ca91be6102b1.png)

如图，不管我WebView内容上拉滑动到哪里，往下拉总会触发下拉刷新，这是为什么呢？是我哪里有使用错误吗？我就是按Demo里的代码来的~

![image](https://cloud.githubusercontent.com/assets/6840638/9516449/455d1a98-4cdb-11e5-986d-c6a3ab9fa0ad.png)

![image](https://cloud.githubusercontent.com/assets/6840638/9516461/59fef05c-4cdb-11e5-9fcc-0ef73149a1d3.png)

![image](https://cloud.githubusercontent.com/assets/6840638/9516478/752089b8-4cdb-11e5-9c31-e51ffb3d8972.png)

**Comment by aqiansunboy** [comment]
return PtrDefaultHandler.checkContentCanBePulledDown(frame, content, header);

Sorry，我发现我忘记调用这段代码了，忽略我的问题哈~

**Comment by liaohuqiu** [comment]
OK, Good luck
