### ISSUE TITLE
多点触控的问题

### ISSUE THREAD

**Issue by alexwan02** [liaohuqiu/android-Ultra-Pull-To-Refresh#146]
多点触控的问题：详情看图

<div>
    <img src="https://github.com/alexwan1989/android-Ultra-Pull-To-Refresh/blob/master/%E5%A4%9A%E7%82%B9%E8%A7%A6%E6%8E%A7%E9%97%AE%E9%A2%98.gif?raw=true">
</div>

**Comment by Aspsine** [comment]
首先需要认知的是目前很多主流的下拉刷新库都存在这个问题。

滑动的原理是：
头部距离 ＝ （当前点.y － 基准点.y） ＋ 头部距离；
基准点 ＝ 当前点；
...

具体原因是因为没有针对多点触控做优化。第二个触控点按下的时候没有更新基准点的位置，第二个触控点在滑动的时候在move事件中依然使用的第一个触控点的基准位置，导致界面跳一下。

解决方案：
监听ACTION_POINTER_DOWN和ACTION_POINTER_UP来更新基准点的位置。

**Comment by t2314862168** [comment]
@alexwan02  自己动手解决了，希望对你有一丁点儿帮助 https://github.com/Chanven/CommonPullToRefresh/issues/60
