### ISSUE TITLE
当listview带header时header被切掉

### ISSUE THREAD

**Issue by bo-siu** [liaohuqiu/android-Ultra-Pull-To-Refresh#147]
当listview带header时header被切掉

**Comment by IceHermes** [comment]
是的,我也遇到了

**Comment by IceHermes** [comment]
添加这句
mPtrFrame.setPtrHandler(new PtrHandler() {
            @Override
            public void onRefreshBegin(PtrFrameLayout frame) {
                updateData();
            }

            @Override
            public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {
                return PtrDefaultHandler.checkContentCanBePulledDown(frame, content, header);
            }
        });

**Comment by liaohuqiu** [comment]
Please make sure the method `checkCanDoRefresh()` return the right value.
