### ISSUE TITLE
[内存泄露] Anonymous runnable causes memory leak

### ISSUE THREAD

**Issue by chenenyu** [liaohuqiu/android-Ultra-Pull-To-Refresh#148]
in.srain.cube.views.ptr.PtrFrameLayout$2.this$0 (anonymous class implements java.lang.Runnable)

使用了LeakCanary,发现PtrFrameLayout中的匿名Runnable持有Activity的引用,造成了内存泄露,望测试.

**Comment by libo591** [comment]
我也发现了这个问题。。希望能提供一个回收函数接口

**Comment by fansmc** [comment]
我使用最新版本1.0.11 还是存在这个问题

**Comment by KIDNG** [comment]
当使用在dialog里面就会出现这种现象，就算在fragment.onDestory方法里面调用了dialog.dismiss()都没用

**Comment by fighterwk** [comment]
我也出现了这个现象，我尝试着修改发现问题有解决的现象
在PtrFrameLayout类的下面方法中
final public void refreshComplete() {
        if (DEBUG) {
            PtrCLog.i(LOG_TAG, "refreshComplete");
        }

        if (mRefreshCompleteHook != null) {
            mRefreshCompleteHook.reset();
        }

        int delay = (int) (mLoadingMinTime - (System.currentTimeMillis() - mLoadingStartTime));
        if (delay <= 0) {
            if (DEBUG) {
                PtrCLog.d(LOG_TAG, "performRefreshComplete at once");
            }
            performRefreshComplete();
        } else {
            // TODO: 2017/9/21 修改:Kyle (问题:performRefreshComplete after delay: 1560841162)
            // 移除所有还未发送的消息
            handler.removeCallbacksAndMessages(null);
            // 加入新的延迟消息逻辑
            handler.postDelayed(new Runnable() {
               @Override
               public void run() {
                    performRefreshComplete();
               }
           }, delay);
//            postDelayed(new Runnable() {
//                @Override
//                public void run() {
//                    performRefreshComplete();
//                }
//            }, delay);
            if (DEBUG) {
                PtrCLog.d(LOG_TAG, "performRefreshComplete after delay: %s", delay);
            }
        }
    }

**Comment by iielse** [comment]
![image](https://user-images.githubusercontent.com/7521943/30733357-37524e0a-9fa9-11e7-964f-bb335c89ca21.png)

@liaohuqiu 
`compile 'in.srain.cube:ultra-ptr:1.0.11'`
如同 @fansmc 所说 最新版本      泄露问题依然存在

**Comment by iielse** [comment]
@fighterwk 
https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh/issues/246
