### ISSUE TITLE
如何禁止下拉？

### ISSUE THREAD

**Issue by qingfengmy** [liaohuqiu/android-Ultra-Pull-To-Refresh#149]
不知有没有setDisable或者类似方法

**Comment by alexwan1989** [comment]
public interface PtrHandler {
                  /**
                   * Check can do refresh or not. For example the content is empty or the first child is in view.
                   * <p/>
                   * {@link in.srain.cube.views.ptr.PtrDefaultHandler#checkContentCanBePulledDown}
                   */
                public boolean checkCanDoRefresh(final PtrFrameLayout frame, final View content, final          View header);

                  /**
                  * When refresh begin
                   *
                  * @param frame
                  */
                public void onRefreshBegin(final PtrFrameLayout frame);
         }


checkCanDoRefresh 始终未false  则禁止下拉  false的时候 会拦截下拉的手势

**Comment by liaohuqiu** [comment]
`setEnabled(false);`
