### ISSUE TITLE
listview嵌套framelayout时,listview无法向上滑动

### ISSUE THREAD

**Issue by syf6490385** [liaohuqiu/android-Ultra-Pull-To-Refresh#152]
listview嵌套framelayout时,向下滑动屏幕,直接触发了下拉刷新,但是listview本身并没有回到最顶部.

**Comment by wade183** [comment]
自己实现PtrHandler或者不要把ListView放在FrameLayout里使用。

**Comment by act262** [comment]
你的Listview应该在PTRLayout里面吧

**Comment by syf6490385** [comment]
已解决，有一个方法没有override~
