### ISSUE TITLE
ptr_rotate_ani_time貌似不起作用

### ISSUE THREAD

**Issue by ccc-rrr** [liaohuqiu/android-Ultra-Pull-To-Refresh#159]
在xml里设置app:ptr_rotate_ani_time = "3000"后mRotateAniTime = arr.getInt(R.styleable.PtrClassicHeader_ptr_rotate_ani_time, mRotateAniTime);获取后的值一直是默认的150，把ptr_rotate_ani_time放进PtrFrameLayout里面后就行了mRotateAniTime = arr.getInt(R.styleable.PtrFrameLayout_ptr_rotate_ani_time, mRotateAniTime);就可以了，请问一下是代码原因还是方法用错了？

**Comment by liaohuqiu** [comment]
嗯，需要放在 `PtrFrameLayout` 中。
