### ISSUE TITLE
如果能支持NestedScrolling就好了233333

### ISSUE THREAD

**Issue by youyi-sizuru** [liaohuqiu/android-Ultra-Pull-To-Refresh#160]
最近想用CoordinatorLayout，但又不想放弃PTR，后来想想还是算了。。。

**Comment by zuocaijian** [comment]
@youyi-sizuru 请问你最后的解决方案是怎样的？

**Comment by wilsonssss** [comment]
@youyi-sizuru @zuocaijian 
Hi man, you should try this way: https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh/issues/207
