### ISSUE TITLE
可否增加判断是否数据刷新成功的回调参数

### ISSUE THREAD

**Issue by PeterJiung** [liaohuqiu/android-Ultra-Pull-To-Refresh#161]
能否给onUIRefreshComplete（boolean ）增加一个boolean参数 判断当前数据是否成功加载 这样可以扩展如果成功加载显示刷新成功并保存刷新时间 如果加载失败则显示加载失败不保存刷新时间
PtrFrameLayout的refreshComplete（boolean ）也增加一个boolean参数来告诉当前是否数据加载成功

**Comment by act262** [comment]
这个数据加载成功与否应该是你来决定的，不是由UI决定的吧，不管你的数据加载失败还是成功，都需要调用刷新完毕，通知UI刷新完毕了，然后你需要根据的当前的数据是否成功填充页面

**Comment by liaohuqiu** [comment]
嗯，正如 @act262 所说。That's right. So I would like to close this issue and thank you for you nice explanation, @act262 . :+1:
