### ISSUE TITLE
动态创建PtrClassicFrameLayout，不能正常显示。

### ISSUE THREAD

**Issue by 86yankai** [liaohuqiu/android-Ultra-Pull-To-Refresh#163]
因为是在onFinishInflate中获取子组件，所以动态创建，mContent 为null..

**Comment by weidongliang123** [comment]
你可以在addView之后手动调取一下PtrFramelayout的onFinishInflate()方法

public void addViewForPtrFrameLayout(View child) {
        super.addView(child);
        if (this.getContentView() == null) {
            this.onFinishInflate();
        }
    }
