### ISSUE TITLE
问个简单的问题哈

### ISSUE THREAD

**Issue by LjxPrime** [liaohuqiu/android-Ultra-Pull-To-Refresh#168]
因为是新手的缘故，对安卓不是太熟悉，所以这个不太会用，文档实在是看不懂所以才问下。
我直接在布局里加入了这个ptr的frame，然后里面是一个scrollview，但是滑动scroll到顶端之后没有任何反应呀，是还要配合java代码才行吗？

**Comment by LjxPrime** [comment]
还有就是Demo实在太复杂了，看不懂，各种fragment和layout都堆一起了，也没列表说明。感觉Demo没必要这么写，最好是一个样式一个Activity和layout，这样很清楚，毕竟不是实际程序没必要的。

**Comment by liaohuqiu** [comment]
你需要实现 `checkCanDoRefresh()` 这个方法，确定可以下拉刷新的时机。 

关于 Demo 的复杂性，谢谢你的建议。I will do my best to make it as simpler as possible.
