### ISSUE TITLE
额额 道个歉

### ISSUE THREAD

**Issue by LjxPrime** [liaohuqiu/android-Ultra-Pull-To-Refresh#169]
刚才确实是我着急了些，不过我的言辞也没什么不当的地方。不过我可以理解，现在国人都比较敏感，在加上大神一般都看不上我们这样的渣渣。我看过作者所谓的哪个QQ群加入须知，而且我也十分讨厌没有任何探索张口就问的人。可是无奈有的时候水平太渣又没人带飞，在加上本就是小众的库，不可能在gg上一查就有解决方案，我也确实看了半天，实在是理解不了。国人不是有那些个经典的理论，比如自己傻逼还说人家做的不好，前半句倒是适合，但我也没说人家做的不好呀~只是觉得可能不太适合我们这种渣渣吧。既然被删了那就不问了，我继续自己琢磨吧，不过看来大大和哪个什么群加入须知上说的可不太一样啊。（大大看完了删除即可，不删也无所谓）

**Comment by LjxPrime** [comment]
额补充说下，我感觉国人的文档一般写的逻辑都比叫奇怪，这也不能怪大大，谁叫都是中国人呐~

**Comment by liaohuqiu** [comment]
请问有什么可以帮助你的？
