### ISSUE TITLE
PtrUIHandler.onUIComplete中添加是否刷新成功标志

### ISSUE THREAD

**Issue by desmond1121** [liaohuqiu/android-Ultra-Pull-To-Refresh#179]
`PtrUIHandler.onUIComplete()`中添加是否刷新成功标志，变成：

    onUIRefreshComplete(PtrFrameLayout frame, boolean success, String errMsg)

添加方法`PtrFrameLayout.refreshComplete(boolean success, String errMsg)`，改动`PtrFrameLayout.refreshComplete()`使其调用`PtrFrameLayout.refreshComplete(true, "")`。

这样一来，传入是否成功刷新的标志，在刷新失败、刷新成功时UI展示不同，给予使用者更多扩展可能性。

**Comment by liaohuqiu** [comment]
刷新是否成功，`refreshComplete()` 是已经知道的。外部可以维护这个状态。

谢谢你的建议，在 Slack 上。
