### ISSUE TITLE
希望上拉加载能支持RecyclerView

### ISSUE THREAD

**Issue by Muyangmin** [liaohuqiu/android-Ultra-Pull-To-Refresh#180]
如果上拉加载能像下拉那样支持所有布局就好了，看到PR里有一位似乎已经做了相关功能，但不知为何没有合并？

**Comment by xiaolongyuan** [comment]
+1

**Comment by xiaotianyilang** [comment]
+1

**Comment by tanranran** [comment]
+1

**Comment by ycdm** [comment]
+1

**Comment by wangjunhui** [comment]
+1

**Comment by scaPEGoatno** [comment]
+1

**Comment by zshu** [comment]
+1

**Comment by nashxk** [comment]
+1

**Comment by yjwfn** [comment]
+1

**Comment by fansmc** [comment]
+1

**Comment by ycdm** [comment]
+1

**Comment by yychai** [comment]
+1  希望楼主把上拉加载更多的功能也合并进来……

**Comment by ysc20052006** [comment]
+1

**Comment by zyyoona7** [comment]
+1

**Comment by chapliny** [comment]
+1

**Comment by stevenchans** [comment]
nice

**Comment by taany6210** [comment]
perfect

**Comment by Mr-GX** [comment]
+1

**Comment by ghost** [comment]
看了一些其他的RecyclerView的项目，上拉加载，基本上都是由Adapter控制的，并不是recyclerView的父view控制。这里有个https://github.com/captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More，不过还是有bug的。

**Comment by captain-miao** [comment]
这么多人～～ 可以参考一下：[RecyclerViewUtils ](https://github.com/captain-miao/RecyclerViewUtils)

**Comment by BeingAStrongHong** [comment]
+1，希望能加上。

**Comment by Muyangmin** [comment]
To All: 这个项目**已经**有上拉加载分支了（请自行寻找），另外[这里](https://github.com/captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More)还有一个通过镜像API方式的上拉实现。具体选用哪个看个人喜好和项目需求，这个Issue下请勿继续提交评论，感谢各位的参与和关注！
