### ISSUE TITLE
两个比较弱的问题

### ISSUE THREAD

**Issue by ywss** [liaohuqiu/android-Ultra-Pull-To-Refresh#182]
我用的 android studio
1、<in.srain.cube.image.CubeImageView
                android:id="@+id/store_house_ptr_image"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

一加这个就报 android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class in.srain.cube.image.CubeImageView 错误

2、如果不用CubeImageView下拉框的文字如何自由配置，没找到方法，用默认的需要先设置语言。。。

**Comment by liaohuqiu** [comment]
1. Android Studio 刷新重启试试。
2. 你把 Demo 跑起来，Demo 中有。
