### ISSUE TITLE
不是说兼容所有 View，今天我把它加在 RecyclerView上，就出现了事件冲突，下拉之后，不能上滑，一上滑就出现刷新header，同时之前旧的Item view 也也会被heade覆盖了，不再出现。求指教

### ISSUE THREAD

**Issue by whistlexie** [liaohuqiu/android-Ultra-Pull-To-Refresh#188]
不是说兼容所有 View，今天我把它加在 RecyclerView上，就出现了事件冲突，下拉之后，不能上滑，一上滑就出现刷新header，同时之前旧的Item view 也也会被heade覆盖了，不再出现。求指教

**Comment by whistlexie** [comment]
哈哈，回顾之前的 issues找到解决方案，特此贴一下
https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh/issues/105

**Comment by liaohuqiu** [comment]
`checkCanDoRefresh()`

**Comment by VinVon** [comment]
我解决的是listView上滑是遇到的相同的问题，获得listView的当前第一个view的int，和listview的第一个firstVisibleItem，修改checkCanDoRefresh返回值，recyclerView还没有实验过，希望对你有帮助。。。




------------------ 原始邮件 ------------------
发件人: "Huqiu Liao";<notifications@github.com>;
发送时间: 2016年1月13日(星期三) 下午5:47
收件人: "liaohuqiu/android-Ultra-Pull-To-Refresh"<android-Ultra-Pull-To-Refresh@noreply.github.com>; 

主题: Re: [android-Ultra-Pull-To-Refresh] 不是说兼容所有 View，今天我把它加在 RecyclerView上，就出现了事件冲突，下拉之后，不能上滑，一上滑就出现刷新header，同时之前旧的Item view 也也会被heade覆盖了，不再出现。求指教 (#188)




Closed #188.
