### ISSUE TITLE
Is it possible to replace a View that is inside PtrFrameLayout

### ISSUE THREAD

**Issue by zhanhui913** [liaohuqiu/android-Ultra-Pull-To-Refresh#194]
I had a list view that when empty, i would like to display something else that would still work with the pull to refresh.
By default in the xml, the list view is already inside, but i tried to programatically replace the list view with another view but with no success.
Anyone has any idea?

**Comment by liaohuqiu** [comment]
You can wrap a list view and the other view by a FrameLayout or the other layout.

```
<PtrFrameLayout
   <FrameLayout
      <ListView
      <EmptyViewForNoSuccess
```

**Comment by zhanhui913** [comment]
I tried something like this, it works with an empty list view, but with a full list view (meaning a list view with more than what the parent allows, it scrolls), I would scroll down but the moment i scroll slightly up, it would pull on the header of ptrFrameLayout, where-as usually it should scroll all the way up to the first index before the header is pulled down.

Not sure if this actually works.

**Comment by zhanhui913** [comment]
Nvm, found bug #38 

        mPtrFrame.setPtrHandler(new PtrHandler() {
            @Override
            public void onRefreshBegin(PtrFrameLayout frame) {
                updateData();
            }

            @Override
            public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {

                // here check $mListView instead of $content
                return PtrDefaultHandler.checkContentCanBePulledDown(frame, mListView, header);
            }
        });

To fix it.

Thanks
