### ISSUE TITLE
disable scroll

### ISSUE THREAD

**Issue by yfsx** [liaohuqiu/android-Ultra-Pull-To-Refresh#198]
hi, how to disable refresh when my recycle view is scrolling? (so the ptr will active pull to refresh only on the top item, not on my all items)
thanks!

**Comment by yfsx** [comment]
i got my personal solution!

first of all, add LinearLayoutManager / Layout manager and set it to recycleview

    recycleView.setLayoutManager(layoutManager);

implement recycleview with addOnScrollListener and then add following code in onScrolled

    @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                //validate ptr to refresh
                ptrFrameLayout.setEnabled(llm.findFirstCompletelyVisibleItemPosition() == 0);
            }


thanks for this great library! cheers!

**Comment by liaohuqiu** [comment]
I would do it in your way :+1: .
