### ISSUE TITLE
在AppBarLayout里添加layout_scrollFlags,  PtrClassicFrameLayout添加layout_behavior存在冲突

### ISSUE THREAD

**Issue by andyxialm** [liaohuqiu/android-Ultra-Pull-To-Refresh#207]
已解决，感谢@chenshuhong 的回答，测试可用解决问题。答案见3L

复现：

```
<android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        app:elevation="0dp">

        <某个LinearLayout的控件
            android:id="@+id/header_digist_bar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:layout_scrollFlags="scroll|enterAlways"/>

    </android.support.design.widget.AppBarLayout>

    <in.srain.cube.views.ptr.PtrClassicFrameLayout
        android:id="@+id/ptr_refresh"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/gray_divider_1"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recycler_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/primary_color"
            android:dividerHeight="@dimen/dimen_10_dip"
            android:footerDividersEnabled="false"/>
    </in.srain.cube.views.ptr.PtrClassicFrameLayout>
```

当RecyclerView无数据时，进行上拉操作，会把AppbarLayout里的控件挤上去(这是正常的)。
此时再下拉，AppbarLayout里的childView无法拉出，只有refresh的header出现

期望结果：无数据时，且AppbarLayout里的子视图未展现完全时，应将AppbarLayout中的子视图下拉至完全，然后再出现下拉刷新的逻辑。

备注：也可能是我使用姿势的问题，若是我使用上的问题，麻烦告知。

**Comment by liuxiangtian** [comment]
AppbarLayout的行为是由RecyclerView的滑动引起的

下拉的时候事件在PtrClassicFrameLayout这里被拦截了，没有被RecyclerView处理，也就无法引起AppbarLayout的变化了。

个人看法，没有验证，可以继承一个@string/appbar_scrolling_view_behavior类，重写事件处理，不要拦截你说的这种情况

**Comment by chenshuhong** [comment]
` PtrHandler ptrHandler=new PtrHandler() {
            
@Override
            public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {
                return verticalOffset==0 &&PtrDefaultHandler.checkContentCanBePulledDown(frame, content, header);
            }
            @Override
            public void onRefreshBegin(PtrFrameLayout frame) {
                currentPage = 1;
                initDates();
            }
        };`

verticalOffset 为applayout的appBarLayout.addOnOffsetChangedListener(this)监听
`
    
@Override
    public void onOffsetChanged(AppBarLayout appBarLayout, int verticalOffset) {
        this.verticalOffset=verticalOffset;
    }`

**Comment by andyxialm** [comment]
@chenshuhong  感谢，可用

**Comment by amsterly** [comment]
厉害

**Comment by zhangchun007** [comment]
牛逼
