### ISSUE TITLE
[问答] 多滑动布局的时候，无法向上滑动

### ISSUE THREAD

**Issue by biaomingzhong** [liaohuqiu/android-Ultra-Pull-To-Refresh#213]
![layout](https://cloud.githubusercontent.com/assets/5178619/14225741/17a4f432-f900-11e5-877d-1033f3aec1a2.png)
实现该布局的时候，左下方那个垂直滑动的recyclerView只能向下滑动，不能向上，一向上就下拉刷新了，这怎么办，是我哪里出错了吗？有什么办法解决这个问题，谢谢

**Comment by MarnonLee** [comment]
我也是遇到这个问题

**Comment by biaomingzhong** [comment]
@liaohuqiu 方便的话，请帮助一下我们，谢谢

**Comment by liaohuqiu** [comment]
你的  `checkCanDoRefresh()` 这个方法实现有问题吧。

**Comment by biaomingzhong** [comment]
@liaohuqiu 首先感谢你愿意付出你的时间帮忙，我使用的是你的library提供的PtrClassicFrameLayout，并不是自定义的，底下那个recyclerView是23.2的LinearLayoutManager，也不是自定义的

**Comment by biaomingzhong** [comment]
使用的是 `PtrClassicDefaultHeader `没有自定义header

**Comment by biaomingzhong** [comment]
@liaohuqiu 谢谢大神提醒，原来还有这么方便的方法可以Override，大赞这个库

**Comment by kingtami** [comment]
感谢此issues,解决了上滑之后不能下拉,一下拉就只能刷新的问题.
frame.setPtrHandler(
                new PtrHandler() {
                    @Override
                    public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {
                        return true;
                    }

```
                @Override
                public void onRefreshBegin(final PtrFrameLayout frame) {
                    refresh();
                }
            }
    );
```

**Comment by ruzhuxiaogu** [comment]
这是正确的写法，demo里都有
 frame.setPtrHandler(new PtrHandler() {
            @Override
            public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {
                return PtrDefaultHandler.checkContentCanBePulledDown(frame, content, header);
            }

```
        @Override
        public void onRefreshBegin(final PtrFrameLayout frame) {
            System.out.println("Refresh");
            refresh();
    });
```

**Comment by ruzhuxiaogu** [comment]
` frame.setPtrHandler(new PtrHandler() {
            @Override
            public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {
                return PtrDefaultHandler.checkContentCanBePulledDown(frame, content, header);
            }

            @Override
            public void onRefreshBegin(final PtrFrameLayout frame) {
                System.out.println("Refresh");
                getUserList();
                /*
                frame.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        frame.refreshComplete();
                    }
                }, 2000);*/
            }
        });`

**Comment by xiohuchi** [comment]
感谢此解决方案
frame.setPtrHandler(new PtrHandler() {
@Override
public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {
return PtrDefaultHandler.checkContentCanBePulledDown(frame, content, header);
}

```
    @Override
    public void onRefreshBegin(final PtrFrameLayout frame) {
        System.out.println("Refresh");
        refresh();
});
```
