### ISSUE TITLE
ListView 只能下拉不能上拉的问题

### ISSUE THREAD

**Issue by maoruibin** [liaohuqiu/android-Ultra-Pull-To-Refresh#221]
当 contentView 是 ListView 时，出现了 只能下拉，不能上拉的问题，效果如下图

![ptr](http://7xr9gx.com1.z0.glb.clouddn.com/ptr.gif)

依赖如下

    compile 'in.srain.cube:ultra-ptr:1.0.11'

我只是用了简单的 ListView + ArrayAdapter 的组合，

        final PtrClassicFrameLayout classicFrameLayout = (PtrClassicFrameLayout) findViewById(R.id.store_house_ptr_frame);

        classicFrameLayout.setPtrHandler(new PtrHandler() {
            @Override
            public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {
               return true;
            }

            @Override
            public void onRefreshBegin(PtrFrameLayout frame) {
                frame.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        classicFrameLayout.refreshComplete();
                    }
                }, 1000);
            }
        });

        ListView listView = (ListView) findViewById(store_house_ptr_list);
        List<String>list = new ArrayList<>();
        list.add("1");
        。。。。。。
        listView.setAdapter(new ArrayAdapter<String>     (this,android.R.layout.simple_list_item_activated_1,list));

**Comment by maoruibin** [comment]
我找到问题的答案了，在设置下拉监听时，我将 checkCanDoRefresh() 的返回值统一返回了 true ,应该返回 
             return PtrDefaultHandler.checkContentCanBePulledDown(frame, content, header);

这样 PtrFrameLayout 会在 ACTION_MOVE 时对 View 是否可以垂直滚动做判断。具体可看源码！

自己还是对源码不够了解！

**Comment by Aiome** [comment]
我返回的是 PtrDefaultHandler.checkContentCanBePulledDown(frame, content, header); 为什么还是不能上滑。。
