### ISSUE TITLE
关于PtrClassicDefaultHeader更新时间的问题

### ISSUE THREAD

**Issue by dzysghr** [liaohuqiu/android-Ultra-Pull-To-Refresh#226]
PtrClassicDefaultHeader有一个runnable不断去更新时间，当下滑不足以刷新而松手时，头部自动隐藏，但这时runnable不会停止，一直在后台setText，导致整个界面一直在onMeasure、onLayout

**Comment by flyfire** [comment]
有stop吧？

**Comment by dzysghr** [comment]
刚才又试了一下，先完整下拉刷新一次，第二次下拉一点然后松开，Log就不断冒信息了。而且我在代码里也没发现头部隐藏后有stop

**Comment by GordenXiao** [comment]
我验证了一下 确实有这个问题

**Comment by GordenXiao** [comment]
解决：onUIReset 中调用一下mLastUpdateTimeUpdater.stop();
