### ISSUE TITLE
下拉完成之后,再下拉还是完成

### ISSUE THREAD

**Issue by BoBoMEe** [liaohuqiu/android-Ultra-Pull-To-Refresh#243]
显示 `更新完成`  后,短时间内下拉还是显示    `更新完成`

**Comment by BoBoMEe** [comment]
找到了方法,之前没看仔细
 ptrFrame.setEnabledNextPtrAtOnce(true);

**Comment by yangyueyue** [comment]
非常感谢 遇到和你同样的问题解决了
