### ISSUE TITLE
这框架真是太烂了，一大堆的bug，作者就撒手不管了么？

### ISSUE THREAD

**Issue by hackware1993** [liaohuqiu/android-Ultra-Pull-To-Refresh#253]

**Comment by lonnyzhang423** [comment]
you can you up

**Comment by hackware1993** [comment]
@zlidentify 确实在计划之中

**Comment by VectorWen** [comment]
@hackware1993 可能作者没有那么多时间了，国内很多项目都是以这样的方式死掉。

**Comment by hackware1993** [comment]
@VectorWen 恩，我觉得一是没有时间，二是别人用框架的方式或是场景不对，导致出了一些奇怪的问题，而框架作者很难复现这些问题，自然也就谈不上解决了

**Comment by VectorWen** [comment]
@hackware1993 开源社区是靠大家来维护的，但在国内很多都是伸手党，想的是拿来就用，如果用不了，就说作者垃圾，说那个那个库垃圾，但试问一下，身为伸手党，有资格说人家的不是吗？

碰到问题的时候：
1. 找问题的根源，如果是自己使用上的问题，那么这个就不是问题，可以以建议的方式改进使用方式
2. 试着去解决，如果解决了那么可以提交代码，这样作者会更愿意来维护这个库。
3. 如果真心解决不了，提问题的时候也应该说清楚一点问题的根源，作者会更愿意来解决这样的问题。

还有一部分人，碰到了问题，解决了，但是不说出来，因为感觉麻烦。这也是国内开源社区弄不出那么多好的项目的原因之一。大家都是为了完成需求，何必较真呢？！

**Comment by yuxingfafu** [comment]
@VectorWen  问下知道这个库是如何混淆的呀非常感谢：）

**Comment by DeluxDJ** [comment]
有什么问题直接说出来就行了，然后是找相对应的解决方案，不是一味让别人帮你弄完啊兄弟
