### ISSUE TITLE
这个下拉刷新先不说好不好，但是注释几乎没有。

### ISSUE THREAD

**Issue by xanaduo** [liaohuqiu/android-Ultra-Pull-To-Refresh#259]
这个下拉刷新先不说好不好，但是注释几乎没有。设置一个头部都不行，简直无语。

**Comment by yzxdmb01** [comment]
加点注释就好了，英文的也行啊

**Comment by VectorWen** [comment]
@xanaduo 小子，你自己差就说自己差就行了，别说人家的库不好，好的代码是不需要注释的，你连看代码的能力都没有，好像你没有资格说人家的做的好不好吧。如果不喜欢，自己写去。

关于注释：
1. 别TMD 的整那么多注释，10 行代码9 行有注释，我是看你代码呢，还是看你注释呢？
2. 最好的注释是名称，变量名、方法名起的好，要TMD 的注释干JJ
3. 一些算法需要加上注释，一大堆if else switch 不是那么好看的
4. ...

**Comment by xanaduo** [comment]
哟哟，别激动
