### ISSUE TITLE
当在ptrframlayout外面嵌套个scrollview是,ptr里面的布局就不会不显示

### ISSUE THREAD

**Issue by asdf19910719** [liaohuqiu/android-Ultra-Pull-To-Refresh#271]
如题,感觉应该是和scrollview里面嵌套listview原理一样,我尝试了下除非给ptrframlayout个固定高度,否则显示不全,想自己重写onmeasure方法,发现
int expandSpec = MeasureSpec.makeMeasureSpec(Integer.MAX_VALUE >> 2,
                MeasureSpec.AT_MOST);
        super.onMeasure(widthMeasureSpec, expandSpec);
这样有问题,这样写显示出来高度超级大,求解...

**Comment by ByteRax** [comment]
用 android.support.v4.widget.NestedScrollView

**Comment by asdf19910719** [comment]
楼上的确定有用?这个和什么scrollview没关系,主要是嵌套导致ptr自身不能测量自身,不对ptr的测量方法作出处理,换什么scrollview都没用的

**Comment by mattxzhang** [comment]
遇到同样的问题，有解决办法么，Scrollview嵌套的时候，里面的ptr内容不显示，在onMeasure里面重写为最大高度也不行

**Comment by asdf19910719** [comment]
protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        if (mHeaderView != null) {
            measureChildWithMargins(mHeaderView, widthMeasureSpec, 0, heightMeasureSpec, 0);
            MarginLayoutParams lp = (MarginLayoutParams) mHeaderView.getLayoutParams();
            mHeaderHeight = mHeaderView.getMeasuredHeight() + lp.topMargin + lp.bottomMargin;
            mPtrIndicator.setHeaderHeight(mHeaderHeight);
        }

        if (mContent != null) {
            measureContentView(mContent, widthMeasureSpec, heightMeasureSpec);
            if (true) {
                //得到ptr里内容的大小
                ViewGroup.MarginLayoutParams lp = (MarginLayoutParams) mContent.getLayoutParams();
                Log.i("测量宽高", "onMeasure content, width:"+getMeasuredWidth()+"--height:"+getMeasuredHeight()+"--margin:"+
                                lp.leftMargin+"-"+lp.topMargin+"-"+lp.rightMargin+"-"+lp.bottomMargin+"child"+mContent.getMeasuredHeight());
                PtrCLog.d(LOG_TAG, "onMeasure, currentPos: %s, lastPos: %s, top: %s",
                        mPtrIndicator.getCurrentPosY(), mPtrIndicator.getLastPosY(), mContent.getTop());
            }
        }
        
        //执行顺序得在测量完子view之后
        int heightMode=MeasureSpec.getMode(heightMeasureSpec);
        if(heightMode==MeasureSpec.UNSPECIFIED){
            //针对外部嵌套scrollview导致hight的UNSPECIFIED情况,直接设置为子viewGroup大小
            setMeasuredDimension(getDefaultSize(getSuggestedMinimumWidth(), widthMeasureSpec),
                    mContent.getMeasuredHeight());
        }else{
            super.onMeasure(widthMeasureSpec, heightMeasureSpec);
        }

这两天重看了下测量这块，已解决，楼上的替换代码到PtrFrameLayout的onMeasure方法就行

**Comment by mattxzhang** [comment]
@asdf19910719 这样高度是出来了，但是不能下拉了，因为固定了为内容的高度

**Comment by asdf19910719** [comment]
不会吧..我这边里面嵌套的是LinearLayout下拉好使啊,你里面嵌套的是什么布局..我想起来了,这个外面的scrollview会拦截掉ptrframlayout的事件,你重写下scrollview在滑动到顶部并判断是下拉操作时事件分发给ptrframlayout才行的.
/**
     * 当条件:在顶部&&正在下拉,不拦截事件(交给子view完成)
     * 其他情况下,事件交由父view(scrollview处理)
     * @param ev
     * @return
     */
    
    public boolean onInterceptTouchEvent(MotionEvent ev) {

        switch (ev.getAction()){
            case MotionEvent.ACTION_DOWN:
                lastY= (int) ev.getRawY();//用getRawY时不需要在ACTION_MOVE里lastY=curY,因为是绝对位置
                mode=NOCONDITION;
                break;
            case MotionEvent.ACTION_MOVE:
                curY=(int) ev.getRawY();
                int direction=lastY-curY;//下滑true;上滑false;
                int yDistance = Math.abs(direction);
                LogUtil.i(getScrollY()+"getScrollY()");
                if(getScrollY()==0 && yDistance> mTouchSlop && direction<0){
                    mode=CONDITION;
                    return false;
                }
                break;
            case MotionEvent.ACTION_UP:
                break;
        }
        return super.onInterceptTouchEvent(ev);
    }

   
    public boolean onTouchEvent(MotionEvent event) {
        if(mode==CONDITION){
            return false;
        }
        return super.onTouchEvent(event);
    }
看看这样好使不...

**Comment by mattxzhang** [comment]
@asdf19910719 有没有邮箱？

**Comment by asdf19910719** [comment]
没看到...我的邮箱:917993668@qq.com
