### ISSUE TITLE
can author give a demo with viewpager? thx

### ISSUE THREAD

**Issue by jiangchao1987** [liaohuqiu/android-Ultra-Pull-To-Refresh#28]
within a viewpager, i see this in PtrFrameLayout, but i also can not solve the conflict simply. thanks!

    public void disableWhenHorizontalMove(boolean disable) {
        mDisableWhenHorizontalMove = disable;
    }

**Comment by jiangchao1987** [comment]
hi,@liaohuqiu U-Ptr can works with viewpager normally!
what's the problem i come across is a bug 
@see http://stackoverflow.com/questions/12322497/onclicklistener-of-child-preventing-the-swipe-of-android-viewpager

thanks, too

**Comment by liaohuqiu** [comment]
I've added a demonstration of `ViewPager`.
