### ISSUE TITLE
下拉头部固定距离

### ISSUE THREAD

**Issue by zjc** [liaohuqiu/android-Ultra-Pull-To-Refresh#281]
我希望下拉的时候，不要断片，类似Pull-zoom的效果。现在下拉以后头部是一张图片，继续往下拉图片和灰色的有断片。如何判断当前的头部高度已经都显示出来呢？我追踪到PtrFrameLayout中的updatePos方法。希望指点一二，thanks
![18320e70db890479a83469799b9b7fe0](https://cloud.githubusercontent.com/assets/1041554/21303180/71c5bfa4-c5f7-11e6-94ef-5419ac04f715.png)

**Comment by zjc** [comment]
现在通过每次下拉改变的change和mHeaderHeight进行对比，但是还是有点卡顿

**Comment by zjc** [comment]
我看了demo里面的Rentals Style，已经解决了，非常感谢，还是要看官方的demo，我们code里面集成的这个已经被改了太多了

**Comment by cjztool** [comment]
请教一下 怎么搞的? Rentals Style 没看明白啊

**Comment by MIkeeJY** [comment]
请教一下 怎么搞的? Rentals Style 没看明白啊

**Comment by MIkeeJY** [comment]
@cjztool   mPtrTensionIndicator = new PtrTensionIndicator();
                   mPtrFrameLayout.setPtrIndicator(mPtrTensionIndicator);

**Comment by biginsect** [comment]
这种方式是不是得写一个drawable？ 当前我的header 还有一些文案和json动画，处理起来麻烦些？ @MIkeeJY
