### ISSUE TITLE
在与ViewPager进行嵌套使用的时候，左右滑动与下拉刷新会有冲突

### ISSUE THREAD

**Issue by zoujoe7750** [liaohuqiu/android-Ultra-Pull-To-Refresh#32]
PtrFrameLayout  与 ViewPager嵌套使用，会出现冲突～

**Comment by liaohuqiu** [comment]
试试这个。`disableWhenHorizontalMove` ，可以参考 #28

**Comment by liaohuqiu** [comment]
Demo 中增加了 ViewPager的示例。你参考Demo即可。

**Comment by TheMarriedBoy** [comment]
在PtrFrameLayout中套嵌一个HorizontalListview会产生滑动冲突~
