### ISSUE TITLE
还是搞不定啊

### ISSUE THREAD

**Issue by byronchh** [liaohuqiu/android-Ultra-Pull-To-Refresh#34]
一个Viewpager 里面全是Fragment的，framgent 里面是Listview，现在的情况是，把listview往下滑，只要滑动超过一个item的高度，在往上拉的过程中，就会出现刷新按钮。~~~~~~~~~~~~~~~~~~~~
试着用listview firstVisbleItem 去判断， 依然不好使~
 
我这种情况应该很多见吧，望大神解答·~

**Comment by liaohuqiu** [comment]
看来我应该提供一个ViewPager内嵌ListView的Demo了。

**Comment by liaohuqiu** [comment]
ViewPager 中嵌入Fragment 的示例已经在Demo中了。请参考DEMO吧。
```
mPtrFrame.disableWhenHorizontalMove(true);
```

这个是重点。

**Comment by byronchh** [comment]
thank u~!!!
