### ISSUE TITLE
How to disable Scrolling while Refreshing?

### ISSUE THREAD

**Issue by MIkeeJY** [liaohuqiu/android-Ultra-Pull-To-Refresh#347]
PtrFrameLayout setEnable(false) not work

**Comment by MIkeeJY** [comment]
@liaohuqiu

**Comment by raquezha** [comment]
I think you should disable recyclerview or nestedscrollview not the PtrFrameLayout

**Comment by MIkeeJY** [comment]
@raquezha your_recyclerView.setLayoutFrozen(true);   I just use this method
