### ISSUE TITLE
How do I add listview with emptyview?  the PtrFrameLayout only can host 2 elements

### ISSUE THREAD

**Issue by qingfengmy** [liaohuqiu/android-Ultra-Pull-To-Refresh#38]
<in.srain.cube.views.ptr.PtrClassicFrameLayout
        android:id="@+id/rotate_header_list_view_frame"
        xmlns:cube_ptr="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/white"
        cube_ptr:ptr_duration_to_close="200"
        cube_ptr:ptr_duration_to_close_header="1000"
        cube_ptr:ptr_keep_header_when_refresh="true"
        cube_ptr:ptr_pull_to_fresh="false"
        cube_ptr:ptr_ratio_of_header_height_to_refresh="1.2"
        cube_ptr:ptr_resistance="1.7">

        <ListView
            android:id="@+id/rotate_header_list_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/primary"
            android:divider="@null"
            android:fadingEdge="none"
            android:listSelector="@android:color/transparent"
            android:paddingLeft="12dp"
            android:paddingRight="12dp"
            android:scrollbarStyle="outsideOverlay"
            android:choiceMode="singleChoice" />

        <TextView
            android:id="@+id/empty"
            android:text="empty view"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />
    </in.srain.cube.views.ptr.PtrClassicFrameLayout>

the above code is wrong, because PtrFrameLayout only can host 2 elements? what can i do?

**Comment by liaohuqiu** [comment]
`PtrFrameLayout` only can host a `Header` and a `ContentView`. Do you wanna put the emptyview in the same level with the `ContentView`?

**Comment by qingfengmy** [comment]
yes, i want add emptyview except header and contentview in PtrFrameLayout and them are same level

**Comment by liaohuqiu** [comment]
You can wrap the emptyview and the `ListView` by a `FrameLayout`, I've added an demo to show how archive that'. The code is in the `dev` branch. Hope that will be helpful.

**Comment by qingfengmy** [comment]
oh, thank you , it is helpfule.

**Comment by qingfengmy** [comment]
<in.srain.cube.views.ptr.PtrClassicFrameLayout
        android:id="@+id/rotate_header_list_view_frame"
        xmlns:cube_ptr="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/white"
        cube_ptr:ptr_duration_to_close="200"
        cube_ptr:ptr_duration_to_close_header="1000"
        cube_ptr:ptr_keep_header_when_refresh="true"
        cube_ptr:ptr_pull_to_fresh="false"
        cube_ptr:ptr_ratio_of_header_height_to_refresh="1.2"
        cube_ptr:ptr_resistance="1.7">

        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <ListView
                android:id="@+id/rotate_header_list_view"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="@color/primary"
                android:divider="@null"
                android:fadingEdge="none"
                android:listSelector="@android:color/transparent"
                android:paddingLeft="12dp"
                android:paddingRight="12dp"
                android:scrollbarStyle="outsideOverlay"
                android:choiceMode="singleChoice" />

            <TextView
                android:id="@+id/empty_view"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"></TextView>
        </FrameLayout>
    </in.srain.cube.views.ptr.PtrClassicFrameLayout>

but do you mean that?

it can't helpful , the emptyView can show well,but the listview's scroll is wrong.

when i drop down, the header is pulling down,but the listview's firstview has not shown? it is wrong,
do you know what i say?

**Comment by liaohuqiu** [comment]
Check this commit. https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh/commit/9bd60db3c50b5ccdb6d93756c97e0dc2c52dfc51

**Comment by Jensen0618** [comment]
遇到了一样的问题，顺利解决，非常感谢二位
