### ISSUE TITLE
Key files in shortage.

### ISSUE THREAD

**Issue by LittlePanpc** [liaohuqiu/android-Ultra-Pull-To-Refresh#39]
Files like dimens.xml or styles.xml lacks. Meanwhile, in.srain.cube.Cube or something like that, is in shortage, too.
Then, I can't run ptr-demo at all.

**Comment by liaohuqiu** [comment]
This project build successfully in Travis CI: https://travis-ci.org/liaohuqiu/android-Ultra-Pull-To-Refresh. I confirm that it can build successfully  under Eclipse / Intellij IDEA / Android Studio.
