### ISSUE TITLE
加入多点触控

### ISSUE THREAD

**Issue by ldwonday** [liaohuqiu/android-Ultra-Pull-To-Refresh#40]
具体参照QQ的下拉刷新，这是目前流行的，很多操作系统也是，例如miui，魅族ui，这样设计很人性化，这就是细节，做好细节才能立于不败之地，如果只是做成现在的样子，那么随便那一个过来都差不多。另外希望加入自动加载更多，没有更多数据显示已经加载全部数据，加入几个接口，用户自己控制就可以了，比如，setHasMoreData(false);//是否有更多数据,setAutoLoadMoreData();//是否自动加载更多数据。

**Comment by dkzwm** [comment]
这位朋友麻烦尊重一下开发者，提意见可以，用随便这次很不合适。这个包做得非常好了，虽然功能不是最全的，但BUG相对较少，且一直在维护。开源项目，你觉得功能太少可以自己修改代码，同为一个写代码的，看你这邮件很不爽




------------------ 原始邮件 ------------------
发件人: "ldwonday";<notifications@github.com>;
发送时间: 2015年1月22日(星期四) 下午4:15
收件人: "liaohuqiu/android-Ultra-Pull-To-Refresh"<android-Ultra-Pull-To-Refresh@noreply.github.com>; 

主题: [android-Ultra-Pull-To-Refresh] 加入多点触控 (#40)




具体参照QQ的下拉刷新，这是目前流行的，很多操作系统也是，例如miui，魅族ui，这样设计很人性化，这就是细节，做好细节才能立于不败之地，如果只是做成现在的样子，那么随便那一个过来都差不多。另外希望加入自动加载更多，没有更多数据显示已经加载全部数据，加入几个接口，用户自己控制就可以了，比如，setHasMoreData(false);//是否有更多数据,setAutoLoadMoreData();//是否自动加载更多数据。

**Comment by liaohuqiu** [comment]
谢谢 @dkzwm 的支持，同时也感谢 @ldwonday 的鞭策和建议。多点触摸支持是一个不错的建议。关于Load More，我短期不会加入到ptr-lib中。PTR 和 Load More 是两个不同的东西。我希望一个工具只做一件事情，并且简单，可依赖。

多点触控的我这里另外开一个issue：https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh/issues/41。

谢谢两位，祝好！
