### ISSUE TITLE
AndroidStaggeredGrid

### ISSUE THREAD

**Issue by f33chobits** [liaohuqiu/android-Ultra-Pull-To-Refresh#43]
Has this lib been tested on AndroidStaggerdGrid(https://github.com/etsy/AndroidStaggeredGrid)?

**Comment by liaohuqiu** [comment]
`PtrFrameLayout` can contain everything. Any problem?

**Comment by f33chobits** [comment]
Well then, the only problem is 'no problem'

**Comment by liaohuqiu** [comment]
Any question, feel free to post here. Happy coding.
