### ISSUE TITLE
Add Support for infinite scroll

### ISSUE THREAD

**Issue by AizazAZ** [liaohuqiu/android-Ultra-Pull-To-Refresh#45]
Add Support for infinite scroll

**Comment by liaohuqiu** [comment]
`infinite scroll`?  For example? 

:)

**Comment by AizazAZ** [comment]
just load more data when read at the end of list.. something like this 

@Override
    public void onScroll(AbsListView view, int firstVisibleItem, int visibleItemCount, int totalItemCount)
    {
        if (totalItemCount < itemCount) {
            this.itemCount = totalItemCount;
            if (totalItemCount == 0) {
                this.isLoading = true; }
        }
 
        if (isLoading && (totalItemCount > itemCount)) {
            isLoading = false;
            itemCount = totalItemCount;
            currentPage++;
        }
 
        if (!isLoading && (totalItemCount - visibleItemCount)<=(firstVisibleItem + bufferItemCount)) {
            loadMore(currentPage + 1, totalItemCount);
            isLoading = true;
        }
    }

**Comment by liaohuqiu** [comment]
load-more? This maybe helpful.  https://github.com/etao-open-source/cube-sdk 
Here is the demo project:   https://github.com/liaohuqiu/android-cube-app/tree/master/src/in/srain/cube/demo/ui/loadmore

**Comment by AizazAZ** [comment]
This is really really excellent :+1:

**Comment by lalongooo** [comment]
This works great @liaohuqiu . Shouldn't you close this "issue"?

**Comment by liaohuqiu** [comment]
@lalongooo  Thank you for your remind.
