### ISSUE TITLE
如何实现content view区域上的背景

### ISSUE THREAD

**Issue by jw2013** [liaohuqiu/android-Ultra-Pull-To-Refresh#51]
能不能请教下大神demo里content view区域上面的所有部分的背景是灰色的是怎么实现的呢(也就是说那个背景的区域和header不是一个layout)？多谢了！！

![效果图](https://camo.githubusercontent.com/9033435ad82be43ccddc8203450f361ee270c724/687474703a2f2f737261696e2d6769746875622e71696e6975646e2e636f6d2f756c7472612d7074722f70756c6c2d746f2d726566726573682e676966)

**Comment by jw2013** [comment]
啊 我明白了 就是再整个layout下面再加了层背景色是么。

**Comment by jw2013** [comment]
我想到怎么做了。

**Comment by liaohuqiu** [comment]
好，这几天到杭州出差，处理issue时间不多。抱歉。

**Comment by jw2013** [comment]
大神威武！
