### ISSUE TITLE
First element of the list get cropped while pulling to refresh for api <11

### ISSUE THREAD

**Issue by berserkore** [liaohuqiu/android-Ultra-Pull-To-Refresh#54]
Using listview or gridview into a PtrClassicFrameLayout has a bug for device < 11.
When pressing and pulling to refresh, make sure to keep pressing and go up and down, you should notice that the first element for the list get cropped. It is like the pull to refresh (PtrClassicFrameLayout) get triggered before the top of the list.
Please check the .gif using the current app of this demo on Genymotion 2.3.7

![bug_less_11](https://cloud.githubusercontent.com/assets/11094066/6305815/2aa097fc-b92e-11e4-8612-71562853c802.gif)

**Comment by berserkore** [comment]
Indeed, PtrDefaultHandler.checkContentCanBePulledDown() in the method checkCanDoRefresh() is randomly triggering over the first item of the list with device <11. So I found out a way to fix this problem. 
instead to use:
```
 @Override
public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {
                    return PtrDefaultHandler.checkContentCanBePulledDown(frame, content, header);
                }
```
Just look when the listview or gridview is no more able to scroll up:
```
@Override
 public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {
                    return !canScrollUp(((GridView) content)); // or cast with ListView
                }

public boolean canScrollUp(View view) {
            if (android.os.Build.VERSION.SDK_INT < 14) {
                if (view instanceof AbsListView) {
                    final AbsListView absListView = (AbsListView) view;
                    return absListView.getChildCount() > 0
                            && (absListView.getFirstVisiblePosition() > 0 || absListView
                            .getChildAt(0).getTop() < absListView.getPaddingTop());
                } else {
                    return view.getScrollY() > 0;
                }
            } else {
                return ViewCompat.canScrollVertically(view, -1);
            }
        }

```

**Comment by liaohuqiu** [comment]
Thank you for your good suggestion and feedback. As described in https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh/issues/5 , it's really a problem. I want implement this function without support package.

**Comment by liaohuqiu** [comment]
It's fixed in the latest release.
