### ISSUE TITLE
在ObservableListView中下拉刷新不能正常工作

### ISSUE THREAD

**Issue by sd6352051** [liaohuqiu/android-Ultra-Pull-To-Refresh#58]
hi 
我使用https://github.com/ksoichiro/Android-ObservableScrollView 和android-Ultra-Pull-To-Refresh，一起使用的时候下拉刷新就不能正常工作了，希望能得到你得帮助或一些建议。谢谢

我使用的类似这个https://github.com/ksoichiro/Android-ObservableScrollView/blob/master/observablescrollview-samples/src/main/java/com/github/ksoichiro/android/observablescrollview/samples/ViewPagerTabListViewActivity.java 

android-Ultra-Pull-To-Refresh也是按照正常配置的，但在下拉时好像是不能正常计算了，上滑后，只要下拉就会响应，不管listview是否在position 0的位置。不知道我还需要做些什么，感谢。

**Comment by liaohuqiu** [comment]
checkCanDoRefresh 这个需要实现正确。offsetY之类得。

**Comment by sd6352051** [comment]
感谢及时回复：）
checkContentCanBePulledDown(in.srain.cube.views.ptr.PtrFrameLayout frame, android.view.View content, android.view.View header)
我有点不太明白是如何计算的，

我在这个方法中需要重写或计算某些东西吗？还是需要修改源码呢？
@Override
    public boolean checkCanDoRefresh(PtrFrameLayout ptrFrameLayout, View view, View view2) {
        return PtrDefaultHandler.checkContentCanBePulledDown(ptrFrameLayout, view, view2);
    }

**Comment by liaohuqiu** [comment]
根据你自己的情况，模仿`PtrDefaultHandler.checkContentCanBePulledDown`，当可以下拉刷新的时候，返回`true`

**Comment by sd6352051** [comment]
谢谢：）
