### ISSUE TITLE
Contents of listvie in fragment will disapear on scroll

### ISSUE THREAD

**Issue by Sorush-moradisani** [liaohuqiu/android-Ultra-Pull-To-Refresh#61]
I have a listview in a framelayout that uses ptr. when I scroll down the upper contents of listview will disappear a
![screenshot_2015-03-15-11-52-26 1](https://cloud.githubusercontent.com/assets/9649165/6655230/a6418d42-cb0a-11e4-8ded-fa8f5f1ba11f.png)
nd when I try to scroll up the refresh layout comes up

**Comment by liaohuqiu** [comment]
You must implement `PtrHandler.checkCanDoRefresh()`. The default implementation has some flaws.

**Comment by Sorush-moradisani** [comment]
it doesn't solve PtrHandler.checkCanDoRefresh()!
![fjj](https://cloud.githubusercontent.com/assets/9649165/6655266/1568b6b2-cb0d-11e4-8e43-3e200939f904.PNG)

**Comment by liaohuqiu** [comment]
The `checkCanDoRefresh()` is a method in interface `PtrHandler`, here is an example:

https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh/blob/master/ptr-demo%2Fsrc%2Fin%2Fsrain%2Fcube%2Fviews%2Fptr%2Fdemo%2Fui%2Fclassic%2FWithListView.java#L60-L70


```
        mPtrFrame.setPtrHandler(new PtrHandler() {
            @Override
            public void onRefreshBegin(PtrFrameLayout frame) {
                updateData();
            }

            @Override
            public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {
                return PtrDefaultHandler.checkContentCanBePulledDown(frame, content, header);
            }
        });
```

**Comment by Sorush-moradisani** [comment]
It still not working! Here is the code:

     @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        rootView = inflater.inflate(R.layout.activity_news, container, false);
        
        final PtrClassicFrameLayout ptrFrame = (PtrClassicFrameLayout) rootView.findViewById(R.id.fragment_rotate_header_with_view_group_frame);
        ptrFrame.setPtrHandler(new PtrHandler() {
            @Override
            public void onRefreshBegin(PtrFrameLayout frame) {
                frame.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        ptrFrame.refreshComplete();
                    }
                }, 1800);
            }

            @Override
            public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {
                return PtrDefaultHandler.checkContentCanBePulledDown(frame, content, header);
            }
        });
        ptrFrame.setLastUpdateTimeRelateObject(this);

        // the following are default settings
        ptrFrame.setResistance(1.7f);
        ptrFrame.setRatioOfHeaderHeightToRefresh(1.2f);
        ptrFrame.setDurationToClose(200);
        ptrFrame.setDurationToCloseHeader(1000);
        // default is false
        ptrFrame.setPullToRefresh(false);
        // default is true
        ptrFrame.setKeepHeaderWhenRefresh(true);

        // scroll then refresh
        // comment in base fragment
        ptrFrame.postDelayed(new Runnable() {
            @Override
            public void run() {
                // ptrFrame.autoRefresh();
            }
        }, 150);

        setupViews(ptrFrame);

**Comment by liaohuqiu** [comment]
Yes, you should implement `checkCanDoRefresh()` to determine when the `ListView` can do refresh:

```
public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {
        // return true when your ListView can refresh
}
```

You can refer the code in `PtrDefaultHandler.checkCanDoRefresh` .

**Comment by Sorush-moradisani** [comment]
Yeah I know that,I'm just testing this codes I'll put contents in it later! I've done everything but still my problem is not solved!

**Comment by liaohuqiu** [comment]
Do you mind pushing your code to github, I will try to fix that for you.

**Comment by Sorush-moradisani** [comment]
Actually for some reasons I cant upload my codes to github but I can email them if its ok to you!

**Comment by liaohuqiu** [comment]
OK, email them to me.

**Comment by Sorush-moradisani** [comment]
Done!

**Comment by liaohuqiu** [comment]
@Sorush-moradisani Sorry, seems that  no email about this issue from you, are you sure .... ?

**Comment by Sorush-moradisani** [comment]
Yes Its done! can you post your email here?! I sent it to srain@php.net

**Comment by liaohuqiu** [comment]
@Sorush-moradisani Sorry, maybe php.net did not transfer that mail to me. 
Can you try this one liaohuqiu@gmail.com.

**Comment by Sorush-moradisani** [comment]
I sent it to your gmail. Sorry again for taking your time so much!

**Comment by liaohuqiu** [comment]
HI, I did not see the `PtrFrameLayout` in you code.

**Comment by liaohuqiu** [comment]
OK, I found that your project is nested.

I found a usage in `NewsFragment`

just change:

```
public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {
    return PtrDefaultHandler.checkContentCanBePulledDown(frame, content, header);
}
```

to

```
public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {
    return PtrDefaultHandler.checkContentCanBePulledDown(frame, feedListView, header);
}
```

**Comment by Sorush-moradisani** [comment]
Tnx a lot! It works perfectly!
