### ISSUE TITLE
Eclipse编译项目的问题解决方法（缺少资源文件的请进来~）。

### ISSUE THREAD

**Issue by Vurtex** [liaohuqiu/android-Ultra-Pull-To-Refresh#62]
rt

**Comment by liaohuqiu** [comment]
eclipse编译？ 没丢失的，需要cube-sdk，你看那个说明。

**Comment by liaohuqiu** [comment]
http://www.liaohuqiu.net/cn/posts/compile-ultra-ptr-in-eclipse/

**Comment by Vurtex** [comment]
感谢回答。已经解决...不过建议我的问题顶置下，可能会很多人不知道。

**Comment by liaohuqiu** [comment]
有道理。

**Comment by msdx** [comment]
对于不知道的，把这个问题在README加粗标明一下就好了。这个问题如果解决就关了吧，不然没点进来把帖子都看完的人还以为一直存在这个问题。

**Comment by liaohuqiu** [comment]
@msdx  谢谢你的提醒。今天一下close了很对fixed的issue。
