### ISSUE TITLE
Work with ViewPage: Difficulty w/ ViewPager

### ISSUE THREAD

**Issue by ynnadkrap** [liaohuqiu/android-Ultra-Pull-To-Refresh#63]
I have a ViewPager that contains 2 pages. I set disableWhenHorizontalMove(true), and this seems to inhibit the invocation of checkCanDoRefresh(). The swiping action registers (checkCanDoRefresh()) infrequently and inconsistently when disableWhenHorizontalMove(true) is set. However, when I set disableWhenHorizontalMove(false), the swipe registers every single time but at the cost of shaky swiping between my ViewPager elements. 

I poked around a bit in the source code, and identified the possible lines that might be causing this problem:

                if (mDisableWhenHorizontalMove && !mPreventForHorizontal && (Math.abs(offsetX) > mPagingTouchSlop || Math.abs(offsetX) > 3 * Math.abs(offsetY))) {
                    if (mPtrIndicator.isInStartPosition()) {
                        mPreventForHorizontal = true;
                    }
                }
                if (mPreventForHorizontal) {
                    return dispatchTouchEventSupper(e);
                }

I think the tolerance for mPreventForHorizontal might be a bit too high.

**Comment by liaohuqiu** [comment]
Yes, you are right, :+1: , this's a problem. Do you have any idea to make this better?

**Comment by ynnadkrap** [comment]
I currently don't have time to look into it, but I'll try later.

**Comment by hebingxing** [comment]
这问题解决了吗，我也遇到这个问题了

**Comment by liaohuqiu** [comment]
This's not a **real** problem. It just a bit too sensitive.
