### ISSUE TITLE
#能否把targetsdk和buildsdk写在一个统一的地方啊，我下下来我都改疯了，现在都不用16或者19的环境了

### ISSUE THREAD

**Issue by hangox** [liaohuqiu/android-Ultra-Pull-To-Refresh#64]

**Comment by liaohuqiu** [comment]
有什么问题么？

**Comment by hangox** [comment]
问题是，我要一个个改，改完才能通过编译(有些地方真的不知道在哪里改)，而且版本号放在一个一个地方也有利于项目开发，（问个问题，你们没有到最后一个自动加载的需求吗）谢谢作者回复

**Comment by feiyu1001** [comment]
麻烦加上  滚动到底部自动加载吧，一般的都需要这个功能

**Comment by liaohuqiu** [comment]
下拉刷新和自动加载更多是两个独立的完全不同的功能。下拉刷新类库中不会加入此功能。如果需要同时使用这两个功能，我在cube-sdk中提供了封装，可以参考这个。https://github.com/liaohuqiu/android-cube-app

**Comment by hangox** [comment]
作者你好，为什么你认为这是完全独立的功能？？可以说说原因吗？？？

**Comment by dkzwm** [comment]
下拉刷新本身和加载更多就不是一回事吧，下拉刷新是在listview外层嵌套viewgroup实现，加载更多是在listview内部实现，作者的下拉刷新控件是封装的嵌套层，是为了更方便给view实现下拉刷新而做的‍
------------------ 原始邮件 ------------------
发件人: "hangox";<notifications@github.com>;
发送时间: 2015年3月24日(星期二) 上午9:47
收件人: "liaohuqiu/android-Ultra-Pull-To-Refresh"<android-Ultra-Pull-To-Refresh@noreply.github.com>; 

主题: Re: [android-Ultra-Pull-To-Refresh] #能否把targetsdk和buildsdk写在一个统一的地方啊，我下下来我都改疯了，现在都不用16或者19的环境了 (#64)



作者你好，为什么你认为这是完全独立的功能？？可以说说原因吗？？？

**Comment by hangox** [comment]
嗯嗯，但是很多下拉加载更多都是实现在viewGroup那里的喔？

**Comment by liaohuqiu** [comment]
@hangox `Ultra-Ptr`目前的设计是为了兼容所有的View，并且直接把头部放到尾部，不美观。有一些类库加载更多是实现在viewGroup中，那样的交互效果，我们认为不够友好，即到底部之后，需要再拉动一下，或者重写`ListView / ScrollView`，到底部之后，可以露出一些尾部。尤其是后者，使得用户必须使用那定制的 `ListView / ScrollView`。 简单可依赖，一个工具就做一件事情,鉴于此，不把 `Ultra-Ptr` 和load-more 放在一起。

**Comment by hangox** [comment]
明白了，谢谢作者
