### ISSUE TITLE
Get NoClassDefFoundError: in.srain.cube.util.CLog’ when I use RentalsSunHeaderView without clog.jar

### ISSUE THREAD

**Issue by guobuping** [liaohuqiu/android-Ultra-Pull-To-Refresh#66]
I use the library in gradle way ``compile 'in.srain.cube:ultra-ptr:1.0.8@aar'``.Everything runs fine when I use MaterialHeader or StoreHouseHeader while if I use RentalsSunHeaderView I will get a error ``java.lang.NoClassDefFoundError: in.srain.cube.util.CLog``. If I add the clog.jar it will be OK but I don't think it is a good idea to import other jar besides the aar in the project.
Thank you very much.

**Comment by liaohuqiu** [comment]
Thank you for your good suggestion.

But `in.srain.cube:clog:1.0.2` is a dependency of `in.srain.cube:ultra-ptr:1.0.8`.

https://oss.sonatype.org/content/repositories/snapshots/in/srain/cube/ultra-ptr/1.0.8.3-SNAPSHOT/ultra-ptr-1.0.8.3-20150312.000055-1.pom

Do you have any better idea?

**Comment by liaohuqiu** [comment]
`CLog` has been removed since `1.0.8.4-SNAPSHOT`. `1.0.8` will be release in days.
