### ISSUE TITLE
频繁的下拉刷新不起作用

### ISSUE THREAD

**Issue by DukeLee1989** [liaohuqiu/android-Ultra-Pull-To-Refresh#69]
您好，我有个疑问，如果我第一次下拉刷新成功后，再快速的下拉刷新发现不起作用了？？
因为onUIReset（）方法还没走，能实现频繁的下拉刷新也可以吗？？？如果可以，请告诉我一个idea，谢谢了。

**Comment by liaohuqiu** [comment]
see #72
