### ISSUE TITLE
Enable Next PTR at Once

### ISSUE THREAD

**Issue by liaohuqiu** [liaohuqiu/android-Ultra-Pull-To-Refresh#72]
At current design, only after `PtrUIHandler.onUIReset` has been called, the next `PTR` can be performed.

Now,  I've add a method `setEnabledNextPtrAtOnce` for this feature.

**Comment by liaohuqiu** [comment]
Since `1.0.8.5-SNAPSHOT`

**Comment by ray007great** [comment]
hi,这个属性使用之后，在刷新时是可以重置刷新的，但是当刷新完成的那么一个瞬间去重置刷新是失效的。。不知道是一个bug，还是我使用的位置和时机不对。。。
