### ISSUE TITLE
Code clean

### ISSUE THREAD

**Issue by edwardaa** [liaohuqiu/android-Ultra-Pull-To-Refresh#73]
For code clean purpose, it's better to move `RentalsSunDrawable` and `RentalsSunHeaderView` to sample module, since *Rentals Sun Style* is a special use case, and as a library it's not appropriate. @liaohuqiu  how do you think?

**Comment by liaohuqiu** [comment]
Yes, It's too special. And what do you think `StoreHouseHeader` ?

**Comment by edwardaa** [comment]
I think the `StoreHouseHeader` more flexible than `RentalsSunHeaderView`, it could be as an built-in component.

**Comment by liaohuqiu** [comment]
Very reasonable. :+1: 

I will move `RentalsSun*` to sample ASAP.
