### ISSUE TITLE
i want  show header when call autoRefresh(true) 

### ISSUE THREAD

**Issue by sd6352051** [liaohuqiu/android-Ultra-Pull-To-Refresh#75]
hi
我希望每次调用ptrFrame.autoRefresh(true);时，能够像手动下拉那样显示header,但我不想设置ptrFrame.setLoadingMinTime(3000); 因为加载的时间是不确定的，有没有一个方法可以在加载时显示header,直到调用mPtrFrameLayout.refreshComplete();时header才隐藏呢，非常感谢

**Comment by liaohuqiu** [comment]
Demo 中的自动刷新，不是你要的效果吗？

**Comment by sd6352051** [comment]
demo 是设置了ptrFrame.setLoadingMinTime(3000); 每次不管加载没加载完都得等3秒，但我想只要调用了mPtrFrameLayout.refreshComplete(); header就消失

**Comment by sd6352051** [comment]
hi,
我知道了，没有仔细看，非常感谢
https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh/blob/master/ptr-demo/src/in/srain/cube/views/ptr/demo/ui/MaterialStyleFragment.java
