### ISSUE TITLE
jcenter - ultra-ptr-1.0.9.aar download failed

### ISSUE THREAD

**Issue by bluhar** [liaohuqiu/android-Ultra-Pull-To-Refresh#78]
https://jcenter.bintray.com/in/srain/cube/ultra-ptr/1.0.9/

> Could not download artifact 'ultra-ptr.aar (in.srain.cube:ultra-ptr:1.0.9)'
   > Could not GET 'https://jcenter.bintray.com/in/srain/cube/ultra-ptr/1.0.9/ultra-ptr-1.0.9.aar'.
      > peer not authenticated

    // Top-level build file where you can add configuration options common to all sub-  projects/modules.

    buildscript {
        repositories {
            jcenter()
       }
        dependencies {
        classpath 'com.android.tools.build:gradle:1.1.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
    }

    allprojects {
    repositories {
        jcenter()
        mavenCentral();
        maven {
            url 'https://oss.sonatype.org/content/repositories/releases'
        }
    }
}

**Comment by liaohuqiu** [comment]
I've tested and downloaded successfully.  Maybe it was a temporary network issue. You can try this version: https://jcenter.bintray.com/in/srain/cube/ultra-ptr/1.0.8/
 or other libraries to check that.

**Comment by bluhar** [comment]
Thanks for your replay. It s okay now.
