### ISSUE TITLE
abortRefresh

### ISSUE THREAD

**Issue by lzhAndroid** [liaohuqiu/android-Ultra-Pull-To-Refresh#79]
当需要点击去触发autoRefresh时，需要在前次refresh没有加载完得情况下，执行最新得autoRefresh操作

**Comment by liaohuqiu** [comment]
`setEnabledNextPtrAtOnce()`

**Comment by lzhAndroid** [comment]
thx.😁

**Comment by BatnettWang** [comment]
1111111

 




------------------ 原始邮件 ------------------
发件人: "Mr.monkey";<notifications@github.com>;
发送时间: 2015年5月28日(星期四) 上午10:45
收件人: "liaohuqiu/android-Ultra-Pull-To-Refresh"<android-Ultra-Pull-To-Refresh@noreply.github.com>; 

主题: Re: [android-Ultra-Pull-To-Refresh] abortRefresh (#79)




thx.
