### ISSUE TITLE
Pull to load more

### ISSUE THREAD

**Issue by android12345** [liaohuqiu/android-Ultra-Pull-To-Refresh#8]
要是把上拉加载更多 集成进去，就无敌了

**Comment by xianyo** [comment]
+1, 期待中

**Comment by IceHermes** [comment]
+1,期待中

2015-01-02 13:42 GMT+08:00 xianyo <notifications@github.com>:

**Comment by chenchongyu** [comment]
+1，期待中   最好是可以设置开关，是否显示“加载更多”

**Comment by grumoon** [comment]
加载更多应该是ContentView自己去实现吧，最好不要放在PTR里面

**Comment by liaohuqiu** [comment]
@grumoon 同意你的观点。

**Comment by music60** [comment]
+1

**Comment by AvatarQing** [comment]
@grumoon @liaohuqiu 为何加载更多不能放在PTR里面，能简单说明下吗？

**Comment by EzimetYusup** [comment]
@AvatarQing  I really agree with u

**Comment by EzimetYusup** [comment]
RecyclerView can add endless scrolling but I do not like it ,it is kind of bad for user interface

**Comment by EzimetYusup** [comment]
@liaohuqiu so r  u gonna add pull to load more interface for this lib?

**Comment by liaohuqiu** [comment]
Probably not. Load more is easy to implement and it's independent from Pull to refresh.

I've implemented load more for `ListView` and `GridView`. If I've plenty of time, I will implement load more for `RecyclerView`

<img src="http://srain-github.qiniudn.com/load-more/load-more-for-grid-view.gif" width="300px" style='border: #f1f1f1 solid 1px' />

<img src="http://srain-github.qiniudn.com/load-more/load-more-for-list-view.gif" width="300px" style='border: #f1f1f1 solid 1px'/>

**Comment by littletanker** [comment]
@liaohuqiu i clone the project but can't find demo for load more for ListView and GridView. r u not push  yet ?

**Comment by liaohuqiu** [comment]
@littletanker  It's here https://github.com/liaohuqiu/android-cube-app

**Comment by EzimetYusup** [comment]
@liaohuqiu  yes it is easy to implement load more feature like GIF above ,but what I was saying is pull up to load more like xlistview https://github.com/Maxwin-z/XListView-Android/wiki

**Comment by liaohuqiu** [comment]
@EzimetYusup Ptr supports all the views, but LoadMore only supports ListView and GridView, (RecycleView will be supported in days), so we should not put these two futures together.

**Comment by EzimetYusup** [comment]
@liaohuqiu  Thanks for replying , waiting for your pull up to   LoadMore feature of RecyclerView

**Comment by Vurtex** [comment]
+1

**Comment by xvjianzhe** [comment]
+1 发自网易邮箱大师 在2015年03月20日 11:17 ，Vurtex(李一轩)写道： +1 — Reply to this email directly or view it on GitHub.

**Comment by DuShuYuan** [comment]
+1

**Comment by sunswy** [comment]
+1

**Comment by gushoubang** [comment]
期待加上拉加载更多

**Comment by liaohuqiu** [comment]
Closed. 

As mentioned in #45 .

And here is a solution for load-more:

https://github.com/etao-open-source/cube-sdk 

Here is the demo project: https://github.com/liaohuqiu/android-cube-app/tree/master/src/in/srain/cube/demo/ui/loadmore

**Comment by KANGOD** [comment]
在给出的 cube-sdk demo 中，是根据不同的 View 分别做不同的处理，使之实现 load more 功能。
把 loadMoreView 作为 View 的一部分，感觉这样耦合太严重了。
尤其是 RecyclerView，需要根据 LayoutManager 做不同处理，还要把 loadMoreView 加到 RecyclerView item 中，实现方式太 dirty。
不同的 View 要用不同的方法来实现同一个功能(load more)，很琐碎。像 ptr 一样，附加一个 footerView 作为 loadMoreView ，封装 load more 这一功能，使之对于 ptr 支持的 View 类型全部支持，会不会是更好的设计呢？

@see https://github.com/liaohuqiu/cube-sdk/issues/66

**Comment by shallowlight** [comment]
我感觉也是，没有上拉加载很多情形都无法使用
