### ISSUE TITLE
PtrFrameLayout嵌套ListView,ListView的Header中有一个ViewPager,手势冲突问题

### ISSUE THREAD

**Issue by hebingxing** [liaohuqiu/android-Ultra-Pull-To-Refresh#82]
PtrFrameLayout嵌套ListView,ListView的Header中有一个ViewPager，disableWhenHorizontalMove设置为true。
这个ViewPager在顶部，这个时候checkCanDoRefresh是为true的，并且当手指滑在ViewPager上时，左右滑动可以很顺利的切换，但是下拉的操作，竟然很大的几率无法触发下拉刷新

**Comment by liaohuqiu** [comment]
Same with this issue: https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh/issues/63. So we would like use #63  to trace this issue. 

By the way, do you have any idea to improve this?
