### ISSUE TITLE
viewpager中某个page中用下拉刷新控件的时候。很卡

### ISSUE THREAD

**Issue by cb269267** [liaohuqiu/android-Ultra-Pull-To-Refresh#86]
page2是带ptr的list的，viewpager首次加载时，page1和page2切换会很卡，而且ptr所包含的listview的item会重复调用requestLayout，会打出很多warning log：requestLayout() improperly called by android.widget.TextView{1f5fd30f V.ED.... ......ID 165,102-453,151 #7f0a0148 app:id/mi_tv_wanna_join} during layout: running second layout pass

尚未有空扒源码，麻烦熟悉的看看是啥回事，效率问题挺大的

**Comment by liaohuqiu** [comment]
1. ViewPager getView有问题
2. ListView 每一项 requestLayout 有问题。
3. 日志能说明一些问题。建议参考。
4. 建议先去掉PTR，排除干扰，调试看看。

**Comment by cb269267** [comment]
确定去掉ptr之后不会打出warning log，正常的listview是没有问题的
