### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by lichangadd** [liaohuqiu/android-Ultra-Pull-To-Refresh#88]
I put a Fragment inside PtrClassicFrameLayout.When I finish my Activity,I found the Activity still in memory.
This is the analyze result from MAT.
![image](https://cloud.githubusercontent.com/assets/8686438/7896611/f12dd244-06f0-11e5-84d9-e36256b04704.png)

**Comment by liaohuqiu** [comment]
It seems like a `Message` leak.  There is also another leak which holds the `ViewRootImpl`.

**Comment by lichangadd** [comment]
Yeah,It's my fault.I call refreshComplete directly(start time is zero),so it has a super long time deply message
