### ISSUE TITLE
sometimes will NullPointerException

### ISSUE THREAD

**Issue by fengivy** [liaohuqiu/android-Ultra-Pull-To-Refresh#92]
java.lang.NullPointerException
in.srain.cube.views.ptr.PtrFrameLayout.sendCancelEvent(PtrFrameLayout.java:900)
in.srain.cube.views.ptr.PtrFrameLayout.updatePos(PtrFrameLayout.java:378)
in.srain.cube.views.ptr.PtrFrameLayout.movePos(PtrFrameLayout.java:365)
in.srain.cube.views.ptr.PtrFrameLayout.access$400(PtrFrameLayout.java:22)
in.srain.cube.views.ptr.PtrFrameLayout$ScrollChecker.run(PtrFrameLayout.java:958)

**Comment by liaohuqiu** [comment]
Which version?

**Comment by fengivy** [comment]
The version name is 1.0.9

**Comment by openproject** [comment]
也碰到过此问题，版本也是1.0.9

**Comment by liaohuqiu** [comment]
Fixed now.
