### ISSUE TITLE
listview添加了header之后 下拉松手的时候界面会抖动

### ISSUE THREAD

**Issue by charleys** [liaohuqiu/android-Ultra-Pull-To-Refresh#95]
调用的是listview.addHeaderView(headerView);

这个问题很影响体验哦。

**Comment by liaohuqiu** [comment]
`listview.addHeaderView(headerView);`?  DEMO 中有这样的现象么？

**Comment by liaohuqiu** [comment]
I closed the issue for no more further feedback. Any question, please reopen it.
